-- Auto-generated by tools/extract_symbols.py
-- Do not edit manually. Regenerate after each build.

local S = {}

-- Global variable RDRAM addresses
S.gGameState = 0x00195AE4
S.gPlayState = 0x00195B04
S.gCurrentLevel = 0x001964EC
S.gPlayer = 0x00196538
S.gCsWasNotSkipped = 0x00195ADC
S.gPracticeScreen = 0x00196D20
S.gPracticeConfig = 0x00196D28
S.gPracticeMenuState = 0x00196DBC
S.gHitCount = 0x0017FD48
S.gPracticeDirectHits = 0x000EEDF0
S.gPracticeDespawns = 0x000EEDFC
S.gActors = 0x00182290
S.gBosses = 0x0018D3C0
S.gScenery = 0x0017FDB0
S.gItems = 0x00191A90
S.gChargeTimers = 0x00195C78
S.gLevelPhase = 0x00196534
S.gPathProgress = 0x00195FD8
S.gSavedPathProgress = 0x00195F68
S.gPracticeCheckpointProgress = 0x000EEB00
S.gIodevActive = 0x000F0280
S.gPracticeSlotTestStatus = 0x00196FA0
S.gPracticeSlotTestFirstLoadedValue = 0x00196FA4
S.gPracticeSlotTestSecondLoadedValue = 0x00196FA8
S.gPracticeSlotTestLoadCalls = 0x00196FAC
S.gPracticeSlotTestSlotCount = 0x00196FB0
S.gPracticeActiveSlot = 0x00196E30
S.gPracticeSlotValidBits = 0x00196E34
S.gPracticeLastSaveResult = 0x00196E38
S.gPracticeLastLoadResult = 0x00196E3C
S.gPracticeSaveDisabled = 0x00196E44
S.sFightCarrier = 0x001BAD70
S.gPracticeForceCarrier = 0x000F0180
S.gPracticeCrossLoadState = 0x00196E88
S.gPracticeCrossLoadSlot = 0x00196E8C
S.gPracticeCrossLoadStartFrame = 0x00196E90
S.gPracticeBgmPending = 0x00196E94
S.gPracticeBgmPendingSeqId = 0x00196E98
S.gPracticeBgmPendingDelay = 0x00196E9C
S.gPracticeSlotMeta = 0x00196E48
S.gControllerHold = 0x000FBB20
S.gControllerPress = 0x000FBB38
S.gGameFrameCount = 0x00196068
S.gNextLevel = 0x0017FCE0
S.gNextLevelPhase = 0x0017FCDE
S.gNextGameState = 0x0017FCE2
S.ovl_i1_VRAM = 0x001A6BA0
S.ovl_i1_VRAM_END = 0x001BB770
S.ovl_i2_VRAM = 0x001A6BA0
S.ovl_i2_VRAM_END = 0x001B5430
S.ovl_i3_VRAM = 0x001A6BA0
S.ovl_i3_VRAM_END = 0x001E3AB0
S.ovl_i4_VRAM = 0x001A6BA0
S.ovl_i4_VRAM_END = 0x001BFC30
S.ovl_i5_VRAM = 0x001A6BA0
S.ovl_i5_VRAM_END = 0x001E64E0
S.ovl_i6_VRAM = 0x001A6BA0
S.ovl_i6_VRAM_END = 0x001C7AD0

-- PracticeConfig field offsets
S.config = {}
S.config.laserStrength = 0x00
S.config.bombCount = 0x04
S.config.lifeCount = 0x08
S.config.goldRingCount = 0x0C
S.config.rightWingState = 0x10
S.config.leftWingState = 0x11
S.config.falcoAlive = 0x14
S.config.slippyAlive = 0x18
S.config.peppyAlive = 0x1C
S.config.showInputDisplay = 0x20
S.config.skipCutscenes = 0x24
S.config.showHudOverlay = 0x28
S.config.showLagFrames = 0x2C
S.config.showSpeed = 0x30
S.config.showChargeTiming = 0x34
S.config.showMissedInputs = 0x38
S.config.showHitTracking = 0x3C
S.config.showHitboxes = 0x40
S.config.showHitboxActors = 0x44
S.config.showHitboxScenery = 0x48
S.config.showHitboxItems = 0x4C
S.config.showHitboxPlayer = 0x50
S.config.showHitboxFlash = 0x54
S.config.showSpawnZones = 0x58
S.config.showSpawnActors = 0x5C
S.config.showSpawnItems = 0x60
S.config.showSpawnScenery = 0x64
S.config.expertMode = 0x68
S.config.longHealth = 0x6C
S.config.showPauseMinimap = 0x70
S.config.showChargeShotMeter = 0x74
S.config.autoFireChargeShot = 0x78
S.config.infHealth = 0x7C
S.config.infBombs = 0x80
S.config.infLives = 0x84
S.config.infBoost = 0x88
S.config.prevPlanetsMask = 0x8C
S.config.macroBindState = 0x90
S.config.macroLoop = 0x94

-- Player struct field offsets
S.player = {}
S.player.pos_x = 0x074
S.player.pos_y = 0x078
S.player.pos_z = 0x07C
S.player.state = 0x1C8

-- Actor (gActors[0]) field offsets
S.actor = {}
S.actor.state = 0x0B8

-- Boss struct field offsets (include/sf64object.h Boss)
S.boss = {}
S.boss.obj_id = 0x002
S.boss.sizeof = 0x408

-- Enum constants
S.const = {}
S.const.GSTATE_MAP = 4
S.const.GSTATE_PLAY = 7
S.const.LEVEL_AQUAS = 13
S.const.LEVEL_AREA_6 = 3
S.const.LEVEL_CORNERIA = 0
S.const.LEVEL_FORTUNA = 3
S.const.LEVEL_KATINA = 4
S.const.LEVEL_METEO = 1
S.const.LEVEL_SECTOR_X = 2
S.const.LEVEL_SECTOR_Y = 2
S.const.LEVEL_SOLAR = 7
S.const.LEVEL_TITANIA = 12
S.const.LEVEL_VENOM_1 = 6
S.const.LEVEL_VENOM_ANDROSS = 9
S.const.LEVEL_ZONESS = 8
S.const.PLAYERSTATE_ACTIVE = 3
S.const.PLAYERSTATE_INIT = 1
S.const.PLAYERSTATE_LEVEL_INTRO = 2
S.const.PLAYERSTATE_STANDBY = 0
S.const.PLAY_INIT = 1
S.const.PLAY_STANDBY = 0
S.const.PLAY_UPDATE = 2
S.const.PMENU_CLOSED = 0
S.const.PMENU_OPEN = 1
S.const.PMENU_OPEN_FROZEN = 2
S.const.PSCREEN_GAMEPLAY = 1
S.const.PSCREEN_LEVEL_SELECT = 0
S.const.SAVE_ERR_SLOT = -2
S.const.SAVE_OK = 0

return S
