-- Auto-generated by tools/extract_symbols.py
-- Do not edit manually. Regenerate after each build.

local S = {}

-- Global variable RDRAM addresses
S.gGameState = 0x00195D34
S.gPlayState = 0x00195D54
S.gCurrentLevel = 0x0019673C
S.gPlayer = 0x00196788
S.gCsWasNotSkipped = 0x00195D2C
S.gPracticeScreen = 0x00196F70
S.gPracticeConfig = 0x00196F78
S.gPracticeMenuState = 0x00197028
S.gHitCount = 0x0017FF98
S.gPracticeStats = 0x001971B0
S.gActors = 0x001824E0
S.gBosses = 0x0018D610
S.gScenery = 0x00180000
S.gItems = 0x00191CE0
S.gChargeTimers = 0x00195EC8
S.gLevelPhase = 0x00196784
S.gPathProgress = 0x00196228
S.gSavedPathProgress = 0x001961B8
S.gPracticeCheckpointProgress = 0x000EEDE0
S.gIodevActive = 0x000F0560
S.gPracticeActiveSlot = 0x00197058
S.gPracticeSlotValidBits = 0x0019705C
S.gPracticeLastSaveResult = 0x00197060
S.gPracticeLastLoadResult = 0x00197064
S.gPracticeSaveDisabled = 0x00197054
S.sFightCarrier = 0x001BAEC0
S.gPracticeForceCarrier = 0x000F0450
S.gPracticeCrossLoadState = 0x001970A8
S.gPracticeCrossLoadSlot = 0x001970AC
S.gPracticeCrossLoadStartFrame = 0x001970B0
S.gPracticeBgmPending = 0x001970B4
S.gPracticeBgmPendingSeqId = 0x001970B8
S.gPracticeBgmPendingDelay = 0x001970BC
S.gPracticeSlotMeta = 0x00197068
S.gControllerHold = 0x000FBD70
S.gControllerPress = 0x000FBD88
S.gGameFrameCount = 0x001962B8
S.gNextLevel = 0x0017FF30
S.gNextLevelPhase = 0x0017FF2E
S.gNextGameState = 0x0017FF32
S.ovl_i1_VRAM = 0x001A6CF0
S.ovl_i1_VRAM_END = 0x001BB8C0
S.ovl_i2_VRAM = 0x001A6CF0
S.ovl_i2_VRAM_END = 0x001B5580
S.ovl_i3_VRAM = 0x001A6CF0
S.ovl_i3_VRAM_END = 0x001E3C00
S.ovl_i4_VRAM = 0x001A6CF0
S.ovl_i4_VRAM_END = 0x001BFD80
S.ovl_i5_VRAM = 0x001A6CF0
S.ovl_i5_VRAM_END = 0x001E6630
S.ovl_i6_VRAM = 0x001A6CF0
S.ovl_i6_VRAM_END = 0x001C7C20

-- PracticeConfig field offsets
S.config = {}
S.config.laserStrength = 0x00
S.config.bombCount = 0x04
S.config.lifeCount = 0x08
S.config.goldRingCount = 0x0C
S.config.rightWingState = 0x10
S.config.leftWingState = 0x11
S.config.falcoAlive = 0x14
S.config.slippyAlive = 0x18
S.config.peppyAlive = 0x1C
S.config.showInputDisplay = 0x20
S.config.skipCutscenes = 0x24
S.config.showHudOverlay = 0x28
S.config.showLagFrames = 0x2C
S.config.showSpeed = 0x30
S.config.showChargeTiming = 0x34
S.config.showMissedInputs = 0x38
S.config.showHitTracking = 0x3C
S.config.showHitboxes = 0x40
S.config.showHitboxActors = 0x44
S.config.showHitboxScenery = 0x48
S.config.showHitboxItems = 0x4C
S.config.showHitboxPlayer = 0x50
S.config.showHitboxFlash = 0x54
S.config.showSpawnZones = 0x58
S.config.showSpawnActors = 0x5C
S.config.showSpawnItems = 0x60
S.config.showSpawnScenery = 0x64
S.config.expertMode = 0x68
S.config.longHealth = 0x6C
S.config.showPauseMinimap = 0x70
S.config.showChargeShotMeter = 0x74
S.config.autoFireChargeShot = 0x78
S.config.infHealth = 0x7C
S.config.infBombs = 0x80
S.config.infLives = 0x84
S.config.infBoost = 0x88
S.config.prevPlanetsMask = 0x8C
S.config.macroBindState = 0x90
S.config.macroLoop = 0x94
S.config.showEnemyHealth = 0x98
S.config.enemyHealthSort = 0x9C
S.config.enemyHealthMinHp = 0xA0
S.config.enemyHealthBossOnly = 0xA4
S.config.enemyHealthHideModels = 0xA8
S.config.hitCount = 0xAC

-- PracticeStats struct field offsets
S.stats = {}
S.stats.kills = 0x00
S.stats.csBonus = 0x04
S.stats.directHits = 0x08
S.stats.escapes = 0x0C
S.stats.crashes = 0x10
S.stats.teamKills = 0x14

-- Player struct field offsets
S.player = {}
S.player.pos_x = 0x074
S.player.pos_y = 0x078
S.player.pos_z = 0x07C
S.player.state = 0x1C8

-- Actor (gActors[0]) field offsets
S.actor = {}
S.actor.obj_status = 0x000
S.actor.obj_id = 0x002
S.actor.obj_pos_x = 0x004
S.actor.obj_pos_y = 0x008
S.actor.obj_pos_z = 0x00C
S.actor.info_bonus = 0x03C
S.actor.index = 0x040
S.actor.iwork_team_id = 0x080
S.actor.iwork_group_id = 0x08C
S.actor.iwork_group_flag = 0x090
S.actor.eventType = 0x0B4
S.actor.state = 0x0B8
S.actor.timer_0C2 = 0x0C2
S.actor.scale = 0x110
S.actor.sizeof = 0x2F4

-- Boss struct field offsets (include/sf64object.h Boss)
S.boss = {}
S.boss.obj_id = 0x002
S.boss.sizeof = 0x408

-- Enum constants
S.const = {}
S.const.EVID_EVENT_HANDLER = 40
S.const.EVID_GRANGA_FIGHTER_1 = 4
S.const.EVID_GRANGA_FIGHTER_2 = 5
S.const.EVID_ME_METEOR_6 = 65
S.const.GSTATE_MAP = 4
S.const.GSTATE_PLAY = 7
S.const.LEVEL_AQUAS = 13
S.const.LEVEL_AREA_6 = 3
S.const.LEVEL_CORNERIA = 0
S.const.LEVEL_FORTUNA = 3
S.const.LEVEL_KATINA = 4
S.const.LEVEL_METEO = 1
S.const.LEVEL_SECTOR_X = 2
S.const.LEVEL_SECTOR_Y = 2
S.const.LEVEL_SOLAR = 7
S.const.LEVEL_TITANIA = 12
S.const.LEVEL_VENOM_1 = 6
S.const.LEVEL_VENOM_ANDROSS = 9
S.const.LEVEL_ZONESS = 8
S.const.OBJ_ACTIVE = 2
S.const.OBJ_ACTOR_EVENT = 200
S.const.OBJ_ACTOR_ME_METEOR_SHOWER_1 = 183
S.const.OBJ_ACTOR_SO_PROMINENCE = 279
S.const.OBJ_DYING = 3
S.const.OBJ_FREE = 0
S.const.OBJ_INIT = 1
S.const.PLAYERSTATE_ACTIVE = 3
S.const.PLAYERSTATE_INIT = 1
S.const.PLAYERSTATE_LEVEL_INTRO = 2
S.const.PLAYERSTATE_STANDBY = 0
S.const.PLAY_INIT = 1
S.const.PLAY_STANDBY = 0
S.const.PLAY_UPDATE = 2
S.const.PMENU_CLOSED = 0
S.const.PMENU_OPEN = 1
S.const.PMENU_OPEN_FROZEN = 2
S.const.PSCREEN_GAMEPLAY = 1
S.const.PSCREEN_LEVEL_SELECT = 0
S.const.SAVE_ERR_SLOT = -2
S.const.SAVE_OK = 0
S.const.TEAM_ID_MAX = 6

return S
