-- Auto-generated by tools/extract_symbols.py
-- Do not edit manually. Regenerate after each build.

local S = {}

-- Global variable RDRAM addresses
S.gGameState = 0x0018B454
S.gPlayState = 0x0018B474
S.gCurrentLevel = 0x0018BE5C
S.gPlayer = 0x0018BEA8
S.gCsWasNotSkipped = 0x0018B44C
S.gPracticeScreen = 0x0018C690
S.gPracticeConfig = 0x0018C698
S.gPracticeMenuState = 0x0018C700
S.gHitCount = 0x001756B8
S.gPracticeDirectHits = 0x000E70F0
S.gPracticeDespawns = 0x000E70FC
S.gActors = 0x00177C00
S.gBosses = 0x00182D30
S.gScenery = 0x00175720
S.gItems = 0x00187400
S.gChargeTimers = 0x0018B5E8
S.gLevelPhase = 0x0018BEA4
S.gPathProgress = 0x0018B948
S.gSavedPathProgress = 0x0018B8D8
S.gPracticeCheckpointProgress = 0x000E6F2C
S.gIodevActive = 0x000E7190
S.gPracticeSlotTestStatus = 0x001A2800
S.gPracticeSlotTestFirstLoadedValue = 0x001A2804
S.gPracticeSlotTestSecondLoadedValue = 0x001A2808
S.gPracticeSlotTestLoadCalls = 0x001A280C
S.gPracticeSlotTestSlotCount = 0x001A2810
S.gPracticeActiveSlot = 0x0018C730
S.gPracticeSlotValidBits = 0x0018C734
S.gPracticeLastSaveResult = 0x0018C738
S.gPracticeLastLoadResult = 0x0018C73C
S.gPracticeSaveDisabled = 0x0018C744
S.ovl_i1_VRAM = 0x001B1880
S.ovl_i1_VRAM_END = 0x001C6430
S.ovl_i2_VRAM = 0x001B1880
S.ovl_i2_VRAM_END = 0x001C0110
S.ovl_i3_VRAM = 0x001B1880
S.ovl_i3_VRAM_END = 0x001EE790
S.ovl_i4_VRAM = 0x001B1880
S.ovl_i4_VRAM_END = 0x001CA910
S.ovl_i5_VRAM = 0x001B1880
S.ovl_i5_VRAM_END = 0x001F11C0
S.ovl_i6_VRAM = 0x001B1880
S.ovl_i6_VRAM_END = 0x001D27B0

-- PracticeConfig field offsets
S.config = {}
S.config.laserStrength = 0x00
S.config.bombCount = 0x04
S.config.lifeCount = 0x08
S.config.rightWingState = 0x0C
S.config.leftWingState = 0x0D
S.config.falcoAlive = 0x10
S.config.slippyAlive = 0x14
S.config.peppyAlive = 0x18
S.config.showInputDisplay = 0x1C
S.config.skipCutscenes = 0x20
S.config.showHudOverlay = 0x24
S.config.showLagFrames = 0x28
S.config.showSpeed = 0x2C
S.config.showChargeTiming = 0x30
S.config.showMissedInputs = 0x34
S.config.showHitTracking = 0x38
S.config.showHitboxes = 0x3C
S.config.showHitboxActors = 0x40
S.config.showHitboxScenery = 0x44
S.config.showHitboxItems = 0x48
S.config.showHitboxPlayer = 0x4C
S.config.showHitboxFlash = 0x50
S.config.showSpawnZones = 0x54
S.config.expertMode = 0x58

-- Player struct field offsets
S.player = {}
S.player.pos_x = 0x074
S.player.pos_y = 0x078
S.player.pos_z = 0x07C
S.player.state = 0x1C8

-- Actor (gActors[0]) field offsets
S.actor = {}
S.actor.state = 0x0B8

-- Enum constants
S.const = {}
S.const.GSTATE_MAP = 4
S.const.GSTATE_PLAY = 7
S.const.LEVEL_CORNERIA = 0
S.const.LEVEL_FORTUNA = 3
S.const.LEVEL_KATINA = 4
S.const.LEVEL_METEO = 1
S.const.LEVEL_SECTOR_Y = 2
S.const.PLAYERSTATE_ACTIVE = 3
S.const.PLAYERSTATE_INIT = 1
S.const.PLAYERSTATE_LEVEL_INTRO = 2
S.const.PLAYERSTATE_STANDBY = 0
S.const.PLAY_INIT = 1
S.const.PLAY_STANDBY = 0
S.const.PLAY_UPDATE = 2
S.const.PSCREEN_GAMEPLAY = 1
S.const.PSCREEN_LEVEL_SELECT = 0
S.const.SAVE_ERR_SLOT = -2
S.const.SAVE_OK = 0

return S
