#!/usr/bin/env python3
"""Extract symbol addresses from the linker map file and write a Lua table.

Usage: python3 tools/extract_symbols.py > tests/symbols.lua

The output is consumed by BizHawk Lua test scripts so they can reference
game variables by name instead of hardcoded addresses.
"""
import re
import sys

MAP_FILE = "build/starfox64.us.rev1.map"

SYMBOLS = [
    "gGameState",
    "gPlayState",
    "gCurrentLevel",
    "gPlayer",
    "gCsWasNotSkipped",
    "gPracticeScreen",
    "gPracticeConfig",
    "gPracticeMenuState",
    "gHitCount",
    "gPracticeDirectHits",
    "gPracticeDespawns",
    "gActors",
    "gBosses",
    "gScenery",
    "gItems",
    "gChargeTimers",
    "gLevelPhase",
    "gPathProgress",
]

# PracticeConfig field offsets (bool = int = 4 bytes, s32 = 4, u8 = 1)
# Struct layout with IDO alignment rules:
#   0x00: LaserStrength laserStrength (s32, 4)
#   0x04: s32 bombCount (4)
#   0x08: s32 lifeCount (4)
#   0x0C: u8 rightWingState (1)
#   0x0D: u8 leftWingState (1)
#   0x0E: 2 bytes padding (align to 4 for bool/int)
#   0x10: bool falcoAlive (4)
#   0x14: bool slippyAlive (4)
#   0x18: bool peppyAlive (4)
#   0x1C: bool showInputDisplay (4)
#   0x20: bool skipCutscenes (4)
#   0x24: bool showHudOverlay (4)
#   0x28: bool showLagFrames (4)
#   0x2C: bool showSpeed (4)
#   0x30: bool showChargeTiming (4)
#   0x34: bool showMissedInputs (4)
#   0x38: bool showHitTracking (4)
#   0x3C: bool showHitboxes (4)
#   0x40: bool showHitboxActors (4)
#   0x44: bool showHitboxScenery (4)
#   0x48: bool showHitboxItems (4)
#   0x4C: bool showHitboxPlayer (4)
#   0x50: bool showHitboxFlash (4)
CONFIG_OFFSETS = {
    "laserStrength":    0x00,
    "bombCount":        0x04,
    "lifeCount":        0x08,
    "rightWingState":   0x0C,
    "leftWingState":    0x0D,
    "falcoAlive":       0x10,
    "slippyAlive":      0x14,
    "peppyAlive":       0x18,
    "showInputDisplay": 0x1C,
    "skipCutscenes":    0x20,
    "showHudOverlay":   0x24,
    "showLagFrames":    0x28,
    "showSpeed":        0x2C,
    "showChargeTiming": 0x30,
    "showMissedInputs": 0x34,
    "showHitTracking":  0x38,
    "showHitboxes":     0x3C,
    "showHitboxActors": 0x40,
    "showHitboxScenery":0x44,
    "showHitboxItems":  0x48,
    "showHitboxPlayer": 0x4C,
    "showHitboxFlash":  0x50,
}

# Player struct field offsets (from include/sf64player.h comments)
PLAYER_OFFSETS = {
    "state": 0x1C8,
}

# Enum constants needed by tests
CONSTANTS = {
    "GSTATE_PLAY":              7,
    "GSTATE_MAP":               4,
    "PLAY_STANDBY":             0,
    "PLAY_INIT":                1,
    "PLAY_UPDATE":              2,
    "PLAYERSTATE_STANDBY":      0,
    "PLAYERSTATE_INIT":         1,
    "PLAYERSTATE_LEVEL_INTRO":  2,
    "PLAYERSTATE_ACTIVE":       3,
    "PSCREEN_LEVEL_SELECT":     0,
    "PSCREEN_GAMEPLAY":         1,
    "LEVEL_CORNERIA":           0,
    "LEVEL_METEO":              1,
    "LEVEL_SECTOR_Y":           2,
    "LEVEL_FORTUNA":            3,
    "LEVEL_KATINA":             4,
}

def kseg0_to_rdram(addr):
    """Convert MIPS KSEG0 address (0x80XXXXXX) to RDRAM offset (0x00XXXXXX)."""
    return addr & 0x1FFFFFFF

def main():
    with open(MAP_FILE) as f:
        map_text = f.read()

    found = {}
    for sym in SYMBOLS:
        match = re.search(rf"0x([0-9a-fA-F]+)\s+{sym}\b", map_text)
        if match:
            found[sym] = int(match.group(1), 16)
        else:
            print(f"-- WARNING: symbol '{sym}' not found in map file", file=sys.stderr)

    print("-- Auto-generated by tools/extract_symbols.py")
    print("-- Do not edit manually. Regenerate after each build.")
    print("")
    print("local S = {}")
    print("")

    print("-- Global variable RDRAM addresses")
    for sym in SYMBOLS:
        if sym in found:
            rdram = kseg0_to_rdram(found[sym])
            print(f"S.{sym} = 0x{rdram:08X}")
    print("")

    print("-- PracticeConfig field offsets")
    print("S.config = {}")
    for field, off in sorted(CONFIG_OFFSETS.items(), key=lambda x: x[1]):
        print(f"S.config.{field} = 0x{off:02X}")
    print("")

    print("-- Player struct field offsets")
    print("S.player = {}")
    for field, off in sorted(PLAYER_OFFSETS.items(), key=lambda x: x[1]):
        print(f"S.player.{field} = 0x{off:03X}")
    print("")

    print("-- Enum constants")
    print("S.const = {}")
    for name, val in sorted(CONSTANTS.items()):
        print(f"S.const.{name} = {val}")
    print("")

    print("return S")

if __name__ == "__main__":
    main()
